// Optional QA: NODE_PATH=<playwright modules> node tests/browser_smoke.cjs
const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(process.env.AML_URL||'http://127.0.0.1:8765/output/graph.html');
  await page.waitForFunction(()=>document.querySelector('#stats').textContent.includes('2248'));
  await page.locator('#insights').click();
  for(const tab of ['Кластеры','Паттерны','Устойчивость','Помощник'])await page.locator('#insightTabs button').filter({hasText:tab}).click();
  await page.locator('#assistantQuestion').fill('Кого смотреть первым?');
  await page.locator('#assistantForm button').click();
  assert.equal(await page.locator('#assistantAnswer .link').count(),20);
  await page.locator('#assistantQuestion').fill('Расскажи кто виноват');
  await page.locator('#assistantForm button').click();
  assert.match(await page.locator('#assistantAnswer').innerText(),/не распознан/);
  const sample=await page.evaluate(()=>{const dst=data.nodes.find(n=>n.fan_in>=2).gid;return {dst,ids:data.edges.filter(e=>e.dst===dst).slice(0,2).map(e=>e.src)}});
  await page.locator('#assistantQuestion').fill('Кто собирает деньги с '+sample.ids.join(' '));
  await page.locator('#assistantForm button').click();
  assert.match(await page.locator('#assistantAnswer').innerText(),new RegExp(sample.dst));
  await page.locator('#closeInsights').click();
  await page.locator('#top button').first().click();
  assert.equal(await page.locator('#top button').count(),30);
  const pathNode=await page.evaluate(()=>data.nodes.find(n=>n.seed_path.length>1).gid);
  await page.locator('#gid').fill(pathNode);await page.locator('#search button').click();
  await page.locator('#route-only').check();
  assert.equal(await page.evaluate(()=>visible.length),await page.evaluate(()=>map.get(selected).seed_path.length));
  await page.locator('#reset').click();
  await page.locator('#insights').click();await page.locator('#insightTabs button').filter({hasText:'Паттерны'}).click();
  await page.locator('#insightBody .link').first().click();
  assert.ok(await page.evaluate(()=>activePath.length>=2&&visible.length===activePath.length));
  await page.locator('#reset').click();await page.locator('#top button').first().click();
  await page.locator('#openCase').click();
  await page.locator('#caseStatus').selectOption('Эскалировано');
  await page.locator('#saveCase').click();
  assert.match(await page.locator('#caseFeedback').innerText(),/основание/);
  await page.locator('#caseComment').fill('Проверить полный входящий поток. <script>alert(1)</script>');
  await page.locator('#saveCase').click();
  assert.match(await page.locator('#caseFeedback').innerText(),/сохранено/);
  let pending=page.waitForEvent('download');await page.locator('#exportCase').click();
  let download=await pending;const stream=await download.createReadStream();let bytes=[];for await(const c of stream)bytes.push(c);
  const exported=JSON.parse(Buffer.concat(bytes).toString());
  assert.equal(exported.rule_version,await page.evaluate(()=>data.rule_version));assert.equal(exported.history.length,1);assert.ok(exported.transactions.length>0);
  pending=page.waitForEvent('download');await page.locator('#exportReport').click();download=await pending;
  bytes=[];for await(const c of await download.createReadStream())bytes.push(c);
  assert.ok(!Buffer.concat(bytes).toString().includes('<script>alert'));
  await page.reload();await page.locator('#top button').first().click();await page.locator('#openCase').click();
  assert.equal(await page.locator('#caseStatus').inputValue(),'Эскалировано');
  await page.locator('#closeCase').click();
  await page.locator('#insights').click();await page.locator('#insightTabs button').filter({hasText:'Устойчивость'}).click();
  if(process.env.AML_SCREENSHOT)await page.screenshot({path:process.env.AML_SCREENSHOT});
  assert.deepEqual(errors,[]);await browser.close();
  console.log('Browser smoke passed: graph, analytics, assistant, cases, persistence, exports, safe text.');
})().catch(e=>{console.error(e);process.exit(1)});
